#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPTDIR=$SCRIPT/monetdb/script

. $SCRIPTDIR/farm.in

echo "Starting server...$FARM"
monetdbd start $FARM
monetdbd get all $FARM
